import type { Metadata } from "next"
import { IBM_Plex_Sans } from "next/font/google"
import "./globals.css"
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/sidebar/AppSidebar"

import React from "react"
import { ClientProvider } from "./ClientProvider"
import { Toaster } from "sonner"
import { SocketProvider } from "@/components/SocketProvider"

const ibm_plex_sans = IBM_Plex_Sans({
    weight: "300",
    subsets: ["cyrillic-ext"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${ibm_plex_sans.className} antialiased dark`}>
                <ClientProvider>
                    <SidebarProvider>
                        <SocketProvider />
                        <AppSidebar />
                        <main>{children}</main>
                        <Toaster />
                    </SidebarProvider>
                </ClientProvider>
            </body>
        </html>
    )
}
