"""Update Requests Table cookies and headers with text

Revision ID: 34d55889f1bf
Revises: 97929e0b2fac
Create Date: 2025-04-19 14:36:27.031868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34d55889f1bf'
down_revision: Union[str, None] = '97929e0b2fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'cookies',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('requests', 'headers',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('requests', 'data',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=3000),
               existing_nullable=True)
    op.alter_column('requests', 'url',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'url',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('requests', 'data',
               existing_type=sa.String(length=3000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('requests', 'headers',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('requests', 'cookies',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###
