"""Updated Request And Response Tables

Revision ID: c2b3ee5e1abc
Revises: ee0b708231d4
Create Date: 2025-04-19 19:47:48.461567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c2b3ee5e1abc'
down_revision: Union[str, None] = 'ee0b708231d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'data',
               existing_type=mysql.VARCHAR(length=3000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('requests', 'url',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('responses', 'data',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('responses', 'url',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('responses', 'data',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('requests', 'url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('requests', 'data',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###
