"""Update Response Table cookies and headers with text

Revision ID: ee0b708231d4
Revises: 34d55889f1bf
Create Date: 2025-04-19 19:24:23.440253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee0b708231d4'
down_revision: Union[str, None] = '34d55889f1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'cookies',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('responses', 'headers',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('responses', 'url',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'url',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('responses', 'headers',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('responses', 'cookies',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
